const Chance = require('chance');
const chance = new Chance();


const generateAvailabilities = () => Array(Math.floor((Math.random() * 10) + 1)).fill(0).map(zero => chance.date({ year: 2017 }));

const celebrities = [
    {
        fullName: 'Rick James',
        imageUrl: 'http://www.wallpaperup.com/uploads/wallpapers/2014/12/25/565421/big_thumb_0aa247830ffab74c6d80a036d0d8be10.jpg',
        hourlyPrice: chance.integer({ min: 100, max: 500 }),
        availabilities: generateAvailabilities(),

    },
    {
        fullName: 'Paul Rudd',
        imageUrl: 'https://i.ytimg.com/vi/MbTC9Unj6eY/maxresdefault.jpg',
        hourlyPrice: chance.integer({ min: 1000, max: 1500 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Tom Cruise',
        imageUrl: 'https://wallpaperscraft.com/image/tom_cruise_2015_actor_101066_3840x2400.jpg',
        hourlyPrice: chance.integer({ min: 101, max: 500 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Jakub Grzegorzewski',
        imageUrl: 'http://wallpapercave.com/wp/WLjJC8e.jpg',
        hourlyPrice: chance.integer({ min: 100000, max: 1500000 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Michael Cera',
        imageUrl: 'http://1.bp.blogspot.com/-xHLr9EFS8R0/TwKeV_Tp7DI/AAAAAAAADDM/eAHlYVHS3Wc/s1600/michael-cera-wallpaper-hd-2-770969.jpg',
        hourlyPrice: chance.integer({ min: 1, max: 100 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Eric Andre',
        imageUrl: 'http://static.spin.com/files/120809_eric.jpeg',
        hourlyPrice: chance.integer({ min: 500, max: 1000 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Louis C.K.',
        imageUrl: 'https://i.ytimg.com/vi/O4EyvdTTnWY/maxresdefault.jpg',
        hourlyPrice: chance.integer({ min: 1000, max: 1500 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Charlie Day',
        imageUrl: 'http://fandomania.com/wp-content/uploads/2013/09/16/fangirls-guide-to-charlie-day-1.jpg',
        hourlyPrice: chance.integer({ min: 1, max: 100 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Donald Glover',
        imageUrl: 'http://wallpapersin4k.net/wp-content/uploads/2017/02/Donald-Glover-Wallpapers.jpg',
        hourlyPrice: chance.integer({ min: 1000, max: 1500 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Betty White',
        imageUrl: 'http://cdn.inquisitr.com/wp-content/uploads/2015/11/betty-white-internet-death-hoax-670x437.jpg',
        hourlyPrice: chance.integer({ min: 1000, max: 1500 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Donald Trump',
        imageUrl: 'https://timedotcom.files.wordpress.com/2017/07/donald-trump-nobody-scared.jpg',
        hourlyPrice: chance.integer({ min: 1, max: 10 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Ellen DeGeneres',
        imageUrl: 'https://assets.ellentv.com/www.ellentv.com/main/default/img/ellen-og-1200x630.jpg',
        hourlyPrice: chance.integer({ min: 1000, max: 1500 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Kate Middleton',
        imageUrl: 'http://ksassets.timeincuk.net/wp/uploads/sites/46/2008/10/Kate-middleton-style-moments.jpg',
        hourlyPrice: chance.integer({ min: 1000, max: 1500 }),
        availabilities: generateAvailabilities(),
    },
    {
        fullName: 'Lisa Kudrow',
        imageUrl: 'https://static.lgbtfansdeservebetter.com/uploads/2016/09/Phoebe-Buffay-Lisa-Kudrow.png',
        hourlyPrice: chance.integer({ min: 1000, max: 1500 }),
        availabilities: generateAvailabilities(),
    },
];


const activities = [

    {
        name: 'Walk down Michigan Ave',
        duration: chance.integer({ min: 1, max: 15 }),
        tags: ['shop', 'city'],
        category: 'Explore',
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/60/82/84/6082848d8dfa4412dce4ad052ff3a4c2.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Camp in the desert',
        duration: chance.integer({ min: 1, max: 15 }),
        tags: ['outside', 'warm', 'adventure'],
        category: 'Adventure',
        imageUrl: 'https://designcontest-com-designcontest.netdna-ssl.com/blog/wp-content/uploads/2016/06/1be9d930234015.56197d97e0679.png',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Beat up Santa',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Holiday',
        tags: ['holiday', 'cold', 'snow', 'adventure'],
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/736x/c5/b1/8f/c5b18f61e863f352fdac67ec835042ec--low-poly-d-design.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Watch Breaking Bad',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Entertainment',
        tags: ['tv', 'date', 'inside'],
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/736x/71/92/7b/71927bab48a1aea621e8b71dfef1db70--low-poly-breaking-bad.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Help the Joker rob a bank',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Illegal',
        tags: ['illegal', 'crazy', 'fun'],
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/aa/2f/67/aa2f675e8851ea5672592728a93e9157.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Take a ride with the Dothraki',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Lifestyle',
        tags: ['adventure', 'warm'],
        imageUrl: 'http://gdj.graphicdesignjunction.com/wp-content/uploads/2014/05/009+low-poly+portrait+illustrations.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Visit a Buddhist temple',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Lifestyle',
        tags: ['religious', 'fun', 'chill'],
        imageUrl: 'http://monumentalfailure.weebly.com/uploads/2/8/4/9/28497135/mfscreenshot-0043_1_orig.png',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Swim across the Pacific Ocean',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Adventure',
        tags: ['water', 'adventure', 'sport'],
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/12/c1/3a/12c13a67a188a108d3fd8adb0c832fbb.png',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Go fishing',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Lifestyle',
        tags: ['chill', 'water'],
        imageUrl: 'https://www.blendernation.com/wp-content/uploads/2017/04/bn_default_header_2-1.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Play Guess Who?',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Entertainment',
        tags: ['inside', 'chill', 'game'],
        imageUrl: 'http://gdj.graphicdesignjunction.com/wp-content/uploads/2014/05/low-poly-illustration-photoshop-tutorials-4.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Re-enact the Lion King',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Entertainment',
        tags: ['family', 'drama', 'movie'],
        imageUrl: 'http://orig15.deviantart.net/23fe/f/2013/198/e/0/the_red_mountains_by_toilettenmassaker-d6dux3c.png',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Trap Harry in the forest',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Adventure',
        tags: ['JK', 'adventure', 'fun'],
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/736x/05/c4/93/05c4934c859b2a6e7a3a95fa8a18537a--polygon-art-art-styles.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Train with King Kai',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Violence',
        tags: ['family', 'drama', 'movie'],
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/f4/ba/c7/f4bac719936e20a8e69f8c4675cbd097.png',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Visit Mars',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Explore',
        tags: ['JK', 'adventure', 'fun'],
        imageUrl: 'http://phandroid.s3.amazonaws.com/wp-content/uploads/2014/07/low_poly_planet_by_sicaida1.png',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Chill with a mutant fish',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Adventure',
        tags: ['family', 'drama', 'movie'],
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/bd/e6/55/bde655388182882b033aa1df00c56ab2.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Identify with Hitler',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Explore',
        tags: ['JK', 'adventure', 'fun'],
        imageUrl: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/4a8acd26076325.563636c15b6e0.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Play arcade games',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Entertainment',
        tags: ['family', 'drama', 'movie'],
        imageUrl: 'https://images2.alphacoders.com/784/784657.png',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Plant a tree',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Lifestyle',
        tags: ['JK', 'adventure', 'fun'],
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/2e/a0/9e/2ea09ee02c6e3bed42a8fd2193823ae4.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Fly',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Adventure',
        tags: ['family', 'fly', 'adventure'],
        imageUrl: 'http://img12.deviantart.net/1e6f/i/2015/326/c/2/up__lowpoly__by_mezaka-d9hly3o.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Parley with pirates',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Adventure',
        tags: ['adventure', 'water', 'fun'],
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/736x/fe/75/3c/fe753c3ca547105b84fc1f01b0ffadd2--game-art-illustration-art.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Engineer something',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Business',
        tags: ['inside', 'build', 'design'],
        imageUrl: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/947c5422394831.56311f69bd576.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Grab a hot dog',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Food & Drink',
        tags: ['food'],
        imageUrl: 'https://s-media-cache-ak0.pinimg.com/564x/e5/87/55/e58755a452fb50e382b6ca680b5112d9.jpg',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
    {
        name: 'Fight Logan',
        duration: chance.integer({ min: 1, max: 15 }),
        category: 'Violence',
        tags: ['violence', 'painful', 'crazy'],
        imageUrl: 'http://www.savvyfalcon.com/wp-content/uploads/2016/07/Wolverine.png',
        location: [chance.floating({ min: -85, max: 85 }), chance.floating({ min: -180, max: 180 })],
    },
];

const users = [

    { firstName: 'Jakub', lastName: 'Grzz', isAdmin: true, email: 'jakub@jakub.jakub', password: '1234' },
    { firstName: 'Annie', lastName: 'King', isAdmin: true, email: 'amking23@gmail.com', password: 'abc' },
    { firstName: 'Rick', lastName: 'Aguayo', isAdmin: true, email: 'rick@gmail.com', password: '123' },
    { firstName: 'Raj', lastName: 'Jar', isAdmin: true, email: 'raj@gmail.com', password: 'password123' },
    { firstName: 'Camden', lastName: 'Ko', isAdmin: false, email: 'badboy@gmail.com', password: 'CamCam' },
    { firstName: 'Jean', lastName: 'ValJean', isAdmin: false, email: 'John@gmail.com', password: 'JohnIsMyPassword' },
    { firstName: 'Jake', lastName: 'Muchen', isAdmin: false, email: 'jake@gmail.com', password: 'jake' },
    { firstName: 'Madelyn', lastName: 'Ram', isAdmin: false, email: 'maddie@gmail.com', password: 'MaDdIePw' },
    { firstName: 'Kevin', lastName: 'Lobo', isAdmin: false, email: 'LadiesOfFullstackPrez@yahoo.com', password: 'LOFSK' },
    { firstName: 'Akshay', lastName: 'Western', isAdmin: false, email: 'akshay@gmail.com', password: 'akshay' },
    { firstName: 'Jason', lastName: 'Hu', isAdmin: false, email: 'JHU@gmail.com', password: 'poop' },
    { firstName: 'Willy', lastName: 'Ready', isAdmin: false, email: 'WILLLLL@gmail.com', password: 'pw123' },
    { firstName: 'Alex', lastName: 'Stauter', isAdmin: false, email: 'BigAl@gmail.com', password: 'Cats' },
    { firstName: 'Brian', lastName: 'Carlisle', isAdmin: false, email: 'bribri@gmail.com', password: 'ilovepuppies' },
    { firstName: 'Connie', lastName: 'Conn', isAdmin: false, email: 'ConArtist@gmail.com', password: 'DogsAndCats123' },
    { firstName: 'Nicholas', lastName: 'Drane', isAdmin: false, email: 'NicPicsRock@gmail.com', password: 'Nickkk' },
    { firstName: 'Jake', lastName: 'Question', isAdmin: false, email: 'jakie@gmail.com', password: 'ILikePink' },
    { firstName: 'Wade', lastName: 'Dee', isAdmin: false, email: 'wade@gmail.com', password: 'flowers' },
    { firstName: 'Ray', lastName: 'Man', isAdmin: false, email: 'RayBan@gmail.com', password: 'green' },
    { firstName: 'Charles', lastName: 'Barkley', isAdmin: false, email: 'charles@gmail.com', password: '348920590fsdf' },
    { firstName: 'John', lastName: 'Smith', isAdmin: false, email: 'js123@gmail.com', password: 'heyGuys' },
    { firstName: 'Kathy', lastName: 'King', isAdmin: false, email: 'AK142@gmail.com', password: 'yoo1242' },
    { firstName: 'Lucy', lastName: 'Loo', isAdmin: false, email: 'lulu@gmail.com', password: 'lulu42' },
    { firstName: 'Ameth', lastName: 'Elizaby', isAdmin: false, email: 'ameth@gmail.com', password: 'monopolyIsFun' },
    { firstName: 'Allie', lastName: 'Kat', isAdmin: false, email: 'Allie@gmail.com', password: 'BigAl' },
    
];

module.exports = { activities, users, celebrities };
